#!/bin/sh
#
# PHP CodeSniffer pre-reveive hook for git
#
# @author Eugene Janusov <esycat@gmail.com>
#
# Partially inspired by pre-commit hook
# by Soenke Ruempler <soenke@ruempler.eu>
#

# Read config
CONFIG_FILE=$(dirname $0)/code-audit.conf
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Config file not found."
    exit 1
fi

. $CONFIG_FILE
. $(dirname $0)/phpcs-prepare

LINT_RETVAL=1

while read oldrev newrev ref; do
    FILES_CHANGED=$(git diff-tree -r $oldrev..$newrev | awk '{print $6}' | egrep "$PHPCS_FILE_PATTERN")

    for filepath in `git diff-tree -r $oldrev..$newrev | awk '{print $6}' | egrep "$PHPCS_FILE_PATTERN"`; do
        OUTPUT=$(git show "$newrev:$filepath" | $PHP_BIN -l 2>&1 1>/dev/null)
        RETVAL=$?

        if [ $RETVAL -ne 0 ]; then
            echo "Auto-review on $filepath failed:"
            echo "$OUTPUT"
			LINT_RETVAL=1
        fi
    done
done

if [ $LINT_RETVAL -ne 0 ] ; then
    exit 1
fi

exit

