#!/bin/bash
#
# PHP CodeSniffer pre-commit hook for git
#
# @author Eugene Janusov <esycat@gmail.com>
#
# Partially inspired by pre-commit hook
# by Soenke Ruempler <soenke@ruempler.eu>
#

# Read config
CONFIG_FILE=$(dirname $0)/code-audit.conf
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Config file not found."
    exit 1
fi

. $CONFIG_FILE
. $(dirname $0)/phpcs-prepare

# Retrieve a list of files in staging area that have been added,
# modified or renamed, but no deletions
FILES_CHANGED=$(git diff-index --name-only --cached --diff-filter=ACMR `git rev-parse --default master --verify HEAD` -- )

LINT_RETVAL=0

for filepath in $FILES_CHANGED; do
    OUTPUT=$($PHP_BIN -l $filepath 2>&1 1>/dev/null)
    RETVAL=$?

    if [ $RETVAL -ne 0 ]; then
        echo "$OUTPUT"
        LINT_RETVAL=1
    fi
done

$REVIEW_CMD $FILES_CHANGED
PHPCS_RETVAL=$?

if [ $LINT_RETVAL -ne 0 ] || [ $PHPCS_RETVAL -ne 0 ]; then
	exit 1
fi

exit

